import type { NextPage } from "next";
import Head from "next/head";

import Header from "../../components/Header";
import CreateOrUpdateClient from "../../containers/CreateOrUpdateClient";

import styles from "../../styles/CriarCliente.module.css";

const CreateCustomer: NextPage = () => {
  /* const { data: customers } = useSWR<Customer[]>("customers", () =>
    fetch("./api/customers/index.ts").then((res) => res.json())
  ); */

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header title="Criar cliente" />

      <div className={styles.formWrapper}>
        <CreateOrUpdateClient />
      </div>
    </div>
  );
};

export default CreateCustomer;
