import type { NextPage } from "next";
import Head from "next/head";
import useSWR from "swr";
import { Customer } from "../../helpers/customer-repo";
import { List, Avatar } from "antd";

import styles from "../../styles/Clientes.module.css";
import Header from "../../components/Header";
import CustomersList from "../../components/CustomersList";

const Customers: NextPage = () => {
  const { data: customers, error } = useSWR<Customer[]>("customers", () =>
    fetch("./api/customers").then((res) => res.json())
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header title="Clientes" />

      <CustomersList customers={customers} isFetching={!customers && !error} />
    </div>
  );
};

export default Customers;
